// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkOptimizer.Storage.Models;

#nullable disable

namespace NetworkOptimizer.Storage.Migrations
{
    [DbContext(typeof(NetworkOptimizerDbContext))]
    [Migration("20251224000000_AddPathAnalysisJson")]
    partial class AddPathAnalysisJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NetworkOptimizer.Storage.Models.Iperf3Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceHost")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("DownloadBitsPerSecond")
                        .HasColumnType("REAL");

                    b.Property<long>("DownloadBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadRetransmits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParallelStreams")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PathAnalysisJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawDownloadJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawUploadJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TestTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("UploadBitsPerSecond")
                        .HasColumnType("REAL");

                    b.Property<long>("UploadBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UploadRetransmits")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Iperf3Results", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
