// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkOptimizer.Storage.Models;

#nullable disable

namespace NetworkOptimizer.Storage.Migrations
{
    [DbContext(typeof(NetworkOptimizerDbContext))]
    [Migration("20251216000000_AddUniFiSshSettings")]
    partial class AddUniFiSshSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");
#pragma warning restore 612, 618
        }
    }
}
