namespace NetworkOptimizer.Reports;

/// <summary>
/// Branding and customization options for report generation
/// Enables MSP white-labeling and custom styling
/// </summary>
public class BrandingOptions
{
    /// <summary>
    /// Company name to display on reports (for MSP white-label)
    /// </summary>
    public string CompanyName { get; set; } = "Ozark Connect";

    /// <summary>
    /// Optional path to company logo image (PNG recommended)
    /// Logo will be displayed in report header
    /// Recommended size: 400x286 pixels (1.4:1 ratio)
    /// </summary>
    public string? LogoPath { get; set; }

    /// <summary>
    /// Color scheme for report styling
    /// </summary>
    public ColorScheme Colors { get; set; } = ColorScheme.OzarkConnect();

    /// <summary>
    /// Whether to show product attribution footer
    /// "Generated by NetworkOptimizer for [CompanyName]"
    /// </summary>
    public bool ShowProductAttribution { get; set; } = true;

    /// <summary>
    /// Product name to use in attribution
    /// </summary>
    public string ProductName { get; set; } = "NetworkOptimizer";

    /// <summary>
    /// Custom footer text (optional)
    /// If provided, replaces default footer
    /// </summary>
    public string? CustomFooter { get; set; }

    /// <summary>
    /// Create default Ozark Connect branding
    /// </summary>
    public static BrandingOptions OzarkConnect() => new()
    {
        CompanyName = "Ozark Connect",
        Colors = ColorScheme.OzarkConnect(),
        ShowProductAttribution = true,
        ProductName = "NetworkOptimizer"
    };

    /// <summary>
    /// Create generic/unbranded report options
    /// </summary>
    public static BrandingOptions Generic() => new()
    {
        CompanyName = "Network Report",
        Colors = ColorScheme.Generic(),
        ShowProductAttribution = false
    };
}

/// <summary>
/// Color scheme for report styling
/// Uses hex color codes
/// </summary>
public class ColorScheme
{
    /// <summary>
    /// Primary brand color (headers, accents) - default: Teal #2E6B7D
    /// </summary>
    public string Primary { get; set; } = "#2E6B7D";

    /// <summary>
    /// Secondary brand color (accent elements) - default: Orange #E87D33
    /// </summary>
    public string Secondary { get; set; } = "#E87D33";

    /// <summary>
    /// Tertiary brand color (additional accents) - default: Blue #215999
    /// </summary>
    public string Tertiary { get; set; } = "#215999";

    /// <summary>
    /// Success/OK color - default: Green #389E3C
    /// </summary>
    public string Success { get; set; } = "#389E3C";

    /// <summary>
    /// Warning/Caution color - default: Yellow #D9A621
    /// </summary>
    public string Warning { get; set; } = "#D9A621";

    /// <summary>
    /// Critical/Error color - default: Red #CC3333
    /// </summary>
    public string Critical { get; set; } = "#CC3333";

    /// <summary>
    /// Light gray for backgrounds - default: #F5F5F5
    /// </summary>
    public string LightGray { get; set; } = "#F5F5F5";

    /// <summary>
    /// Text color - default: Black #000000
    /// </summary>
    public string Text { get; set; } = "#000000";

    /// <summary>
    /// Secondary text color - default: Gray #666666
    /// </summary>
    public string TextSecondary { get; set; } = "#666666";

    /// <summary>
    /// Create Ozark Connect color scheme
    /// Based on existing brand colors from Python reference
    /// </summary>
    public static ColorScheme OzarkConnect() => new()
    {
        Primary = "#2E6B7D",    // BRAND_TEAL - Dark teal for headers
        Secondary = "#E87D33",   // BRAND_ORANGE - Orange accent
        Tertiary = "#215999",    // BRAND_BLUE - Dark blue
        Success = "#389E3C",     // BRAND_GREEN - Success green
        Warning = "#D9A621",     // BRAND_YELLOW - Caution yellow
        Critical = "#CC3333",    // BRAND_RED - Warning red
        LightGray = "#F5F5F5",
        Text = "#000000",
        TextSecondary = "#666666"
    };

    /// <summary>
    /// Create generic/professional color scheme
    /// </summary>
    public static ColorScheme Generic() => new()
    {
        Primary = "#1F4788",     // Professional blue
        Secondary = "#5C7A99",   // Light blue
        Tertiary = "#2C3E50",    // Dark gray-blue
        Success = "#27AE60",     // Green
        Warning = "#F39C12",     // Orange
        Critical = "#E74C3C",    // Red
        LightGray = "#ECF0F1",
        Text = "#000000",
        TextSecondary = "#7F8C8D"
    };

    /// <summary>
    /// Create high-contrast color scheme (for accessibility)
    /// </summary>
    public static ColorScheme HighContrast() => new()
    {
        Primary = "#000080",     // Navy blue
        Secondary = "#4169E1",   // Royal blue
        Tertiary = "#191970",    // Midnight blue
        Success = "#006400",     // Dark green
        Warning = "#FF8C00",     // Dark orange
        Critical = "#8B0000",    // Dark red
        LightGray = "#F0F0F0",
        Text = "#000000",
        TextSecondary = "#333333"
    };

    /// <summary>
    /// Parse hex color to RGB components (0-1 range for PDF libraries)
    /// </summary>
    public static (float R, float G, float B) HexToRgb(string hex)
    {
        hex = hex.TrimStart('#');
        if (hex.Length != 6)
            throw new ArgumentException("Hex color must be 6 characters (RRGGBB)", nameof(hex));

        int r = Convert.ToInt32(hex.Substring(0, 2), 16);
        int g = Convert.ToInt32(hex.Substring(2, 2), 16);
        int b = Convert.ToInt32(hex.Substring(4, 2), 16);

        return (r / 255f, g / 255f, b / 255f);
    }

    /// <summary>
    /// Get RGB components for primary color
    /// </summary>
    public (float R, float G, float B) GetPrimaryRgb() => HexToRgb(Primary);

    /// <summary>
    /// Get RGB components for secondary color
    /// </summary>
    public (float R, float G, float B) GetSecondaryRgb() => HexToRgb(Secondary);

    /// <summary>
    /// Get RGB components for success color
    /// </summary>
    public (float R, float G, float B) GetSuccessRgb() => HexToRgb(Success);

    /// <summary>
    /// Get RGB components for warning color
    /// </summary>
    public (float R, float G, float B) GetWarningRgb() => HexToRgb(Warning);

    /// <summary>
    /// Get RGB components for critical color
    /// </summary>
    public (float R, float G, float B) GetCriticalRgb() => HexToRgb(Critical);
}
