using System.Reflection;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace NetworkOptimizer.Reports;

/// <summary>
/// Professional PDF report generator using QuestPDF
/// Generates comprehensive network audit reports with Ozark Connect branding
/// </summary>
public class PdfReportGenerator
{
    private readonly BrandingOptions _branding;
    private byte[]? _logoBytes;

    public PdfReportGenerator(BrandingOptions? branding = null)
    {
        _branding = branding ?? BrandingOptions.OzarkConnect();

        // Configure QuestPDF license (Community license)
        QuestPDF.Settings.License = LicenseType.Community;

        // Load logo from embedded resource
        LoadLogoFromResources();
    }

    private void LoadLogoFromResources()
    {
        try
        {
            var assembly = Assembly.GetExecutingAssembly();
            var resourceName = "NetworkOptimizer.Reports.Resources.logo.png";

            using var stream = assembly.GetManifestResourceStream(resourceName);
            if (stream != null)
            {
                using var ms = new MemoryStream();
                stream.CopyTo(ms);
                _logoBytes = ms.ToArray();
            }
        }
        catch
        {
            // Logo not available - continue without it
            _logoBytes = null;
        }
    }

    /// <summary>
    /// Generate PDF report and save to file
    /// </summary>
    public void GenerateReport(ReportData data, string outputPath)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.Letter);
                page.Margin(0.5f, Unit.Inch);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Black));

                page.Header().Element(c => ComposeHeader(c, data));
                page.Content().Element(c => ComposeContent(c, data));
                page.Footer().Element(c => ComposeFooter(c, data));
            });
        }).GeneratePdf(outputPath);
    }

    /// <summary>
    /// Generate PDF report and return as byte array
    /// </summary>
    public byte[] GenerateReportBytes(ReportData data)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.Letter);
                page.Margin(0.5f, Unit.Inch);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(9).FontColor(Colors.Black));

                page.Header().Element(c => ComposeHeader(c, data));
                page.Content().Element(c => ComposeContent(c, data));
                page.Footer().Element(c => ComposeFooter(c, data));
            });
        }).GeneratePdf();
    }

    private void ComposeHeader(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);

        container.Column(column =>
        {
            // Logo (from embedded resource)
            if (_logoBytes != null && _logoBytes.Length > 0)
            {
                column.Item().AlignLeft().MaxWidth(1.5f, Unit.Inch).Image(_logoBytes);
                column.Item().PaddingTop(10);
            }

            // Title
            column.Item()
                .AlignCenter()
                .Text($"{data.ClientName} Network Port Audit Report")
                .FontSize(22)
                .Bold()
                .FontColor(primaryColor);

            // Generated date
            column.Item()
                .AlignLeft()
                .PaddingTop(6)
                .Text($"Generated: {data.GeneratedAt:MMMM dd, yyyy}")
                .FontSize(10)
                .FontColor(Colors.Grey.Medium);

            column.Item().PaddingBottom(10).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposeFooter(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            column.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
            column.Item().PaddingTop(5);

            if (!string.IsNullOrEmpty(_branding.CustomFooter))
            {
                column.Item()
                    .AlignCenter()
                    .Text(_branding.CustomFooter)
                    .FontSize(8)
                    .FontColor(Colors.Grey.Medium);
            }
            else if (_branding.ShowProductAttribution)
            {
                column.Item()
                    .AlignCenter()
                    .Text(text =>
                    {
                        text.Span("Generated by ").FontSize(8).FontColor(Colors.Grey.Medium);
                        text.Span(_branding.ProductName).FontSize(8).FontColor(Colors.Grey.Medium).Bold();
                        text.Span($" for {_branding.CompanyName}").FontSize(8).FontColor(Colors.Grey.Medium);
                        text.Span($" | {data.GeneratedAt:yyyy-MM-dd HH:mm}").FontSize(8).FontColor(Colors.Grey.Lighten1);
                    });
            }
        });
    }

    private void ComposeContent(IContainer container, ReportData data)
    {
        container.Column(column =>
        {
            // Network Reference
            column.Item().Element(c => ComposeNetworkReference(c, data));

            // Executive Summary
            column.Item().PaddingTop(20).Element(c => ComposeExecutiveSummary(c, data));

            // Action Items
            column.Item().PaddingTop(20).Element(c => ComposeActionItems(c, data));

            // Page break before switch details
            column.Item().PageBreak();

            // Switch Details
            column.Item().Element(c => ComposeSwitchDetails(c, data));

            // Port Security Summary
            column.Item().PageBreak();
            column.Item().Element(c => ComposePortSecuritySummary(c, data));
        });
    }

    private void ComposeNetworkReference(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);
        var lightGray = GetColor(_branding.Colors.LightGray);

        container.Column(column =>
        {
            column.Item()
                .PaddingBottom(10)
                .Text("Network Reference")
                .FontSize(16)
                .Bold()
                .FontColor(primaryColor);

            if (data.Networks.Any())
            {
                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2.5f);
                        columns.RelativeColumn(1f);
                        columns.RelativeColumn(2f);
                    });

                    // Header
                    table.Header(header =>
                    {
                        header.Cell().Background(lightGray).Padding(6)
                            .Text("Network").Bold().FontSize(9);
                        header.Cell().Background(lightGray).Padding(6)
                            .Text("VLAN").Bold().FontSize(9);
                        header.Cell().Background(lightGray).Padding(6)
                            .Text("Subnet").Bold().FontSize(9);
                    });

                    // Rows
                    var sortedNetworks = data.Networks.OrderBy(n => n.VlanId).ToList();
                    foreach (var network in sortedNetworks)
                    {
                        var vlanStr = network.VlanId == 1
                            ? $"{network.VlanId} (native)"
                            : network.VlanId.ToString();

                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(network.Name).FontSize(9);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(vlanStr).FontSize(9);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(network.Subnet).FontSize(9);
                    }
                });
            }
        });
    }

    private void ComposeExecutiveSummary(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);
        var successColor = GetColor(_branding.Colors.Success);
        var warningColor = GetColor(_branding.Colors.Warning);
        var criticalColor = GetColor(_branding.Colors.Critical);

        container.Column(column =>
        {
            column.Item()
                .PaddingBottom(10)
                .Text("Executive Summary")
                .FontSize(16)
                .Bold()
                .FontColor(primaryColor);

            // Security Posture Rating
            string ratingText;
            string ratingColor;

            switch (data.SecurityScore.Rating)
            {
                case SecurityRating.Excellent:
                    ratingText = "EXCELLENT";
                    ratingColor = successColor;
                    break;
                case SecurityRating.Good:
                    ratingText = "GOOD";
                    ratingColor = successColor;
                    break;
                case SecurityRating.Fair:
                    ratingText = "FAIR";
                    ratingColor = warningColor;
                    break;
                case SecurityRating.NeedsWork:
                    ratingText = "NEEDS ATTENTION";
                    ratingColor = criticalColor;
                    break;
                default:
                    ratingText = "UNKNOWN";
                    ratingColor = Colors.Grey.Medium;
                    break;
            }

            column.Item()
                .PaddingBottom(10)
                .Text($"Overall Security Posture: {ratingText}")
                .FontSize(11)
                .Bold()
                .FontColor(ratingColor);

            // Hardening measures
            if (data.HardeningNotes.Any())
            {
                column.Item()
                    .PaddingBottom(4)
                    .Text("Hardening measures already in place:")
                    .FontSize(9);

                foreach (var note in data.HardeningNotes)
                {
                    column.Item()
                        .PaddingLeft(10)
                        .PaddingBottom(2)
                        .Text($"• {note}")
                        .FontSize(9);
                }
            }

            // Topology notes
            if (data.TopologyNotes.Any())
            {
                column.Item().PaddingTop(6);
                foreach (var note in data.TopologyNotes)
                {
                    column.Item()
                        .PaddingBottom(2)
                        .Text($"• {note}")
                        .FontSize(9);
                }
            }
        });
    }

    private void ComposeActionItems(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);
        var criticalColor = GetColor(_branding.Colors.Critical);
        var warningColor = GetColor(_branding.Colors.Warning);
        var successColor = GetColor(_branding.Colors.Success);

        container.Column(column =>
        {
            column.Item()
                .PaddingBottom(10)
                .Text("Action Items")
                .FontSize(16)
                .Bold()
                .FontColor(primaryColor);

            if (!data.CriticalIssues.Any() && !data.RecommendedImprovements.Any())
            {
                column.Item()
                    .Text("No action items - all checks passed.")
                    .FontSize(11)
                    .Bold()
                    .FontColor(successColor);
                return;
            }

            // Critical Issues
            if (data.CriticalIssues.Any())
            {
                column.Item()
                    .PaddingBottom(6)
                    .Text($"Critical ({data.CriticalIssues.Count})")
                    .FontSize(10)
                    .Bold()
                    .FontColor(criticalColor);

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1.6f);
                        columns.RelativeColumn(1.0f);
                        columns.RelativeColumn(2.4f);
                        columns.RelativeColumn(2.0f);
                    });

                    // Header
                    var headerBg = GetColor(_branding.Colors.Primary);
                    table.Header(header =>
                    {
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Device").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Port").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Issue").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Action").Bold().FontSize(8).FontColor(Colors.White);
                    });

                    // Rows
                    foreach (var issue in data.CriticalIssues)
                    {
                        var portText = issue.PortIndex.HasValue
                            ? $"{issue.PortIndex} ({issue.PortName})"
                            : issue.PortName;

                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(issue.SwitchName).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(portText).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(issue.Message).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(issue.RecommendedAction).FontSize(8);
                    }
                });

                column.Item().PaddingBottom(10);
            }

            // Recommended Improvements
            if (data.RecommendedImprovements.Any())
            {
                column.Item()
                    .PaddingBottom(6)
                    .Text($"Recommended ({data.RecommendedImprovements.Count})")
                    .FontSize(10)
                    .Bold()
                    .FontColor(warningColor);

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(1.6f);
                        columns.RelativeColumn(1.0f);
                        columns.RelativeColumn(3.0f);
                        columns.RelativeColumn(1.4f);
                    });

                    // Header
                    var headerBg = GetColor(_branding.Colors.Primary);
                    table.Header(header =>
                    {
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Device").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Port").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Issue").Bold().FontSize(8).FontColor(Colors.White);
                        header.Cell().Background(headerBg).Padding(6)
                            .Text("Status").Bold().FontSize(8).FontColor(Colors.White);
                    });

                    // Rows
                    foreach (var issue in data.RecommendedImprovements)
                    {
                        var portText = issue.PortIndex.HasValue
                            ? $"{issue.PortIndex} ({issue.PortName})"
                            : issue.PortName;

                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(issue.SwitchName).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(portText).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text(issue.Message).FontSize(8);
                        table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                            .Text("Pending").FontSize(8);
                    }
                });
            }
        });
    }

    private void ComposeSwitchDetails(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);
        var criticalColor = GetColor(_branding.Colors.Critical);

        container.Column(column =>
        {
            foreach (var switchDevice in data.Switches)
            {
                var switchType = switchDevice.IsGateway ? "Gateway" : "Switch";

                column.Item()
                    .PaddingBottom(8)
                    .Text($"[{switchType}] {switchDevice.Name} ({switchDevice.ModelName})")
                    .FontSize(12)
                    .Bold()
                    .FontColor(primaryColor);

                // Port table
                column.Item().Element(c => ComposePortTable(c, switchDevice));

                // Notes
                var notes = new List<string>();

                // MAC ACL support note
                if (switchDevice.MaxCustomMacAcls == 0)
                {
                    notes.Add($"Note: {switchDevice.ModelName} doesn't support MAC ACLs (max_custom_mac_acls=0)");
                }

                // Excluded VLANs notes
                foreach (var port in switchDevice.Ports)
                {
                    if (port.ExcludedNetworks.Any())
                    {
                        var excludedStr = string.Join(", ", port.ExcludedNetworks);
                        notes.Add($"Port {port.PortIndex} excludes: {excludedStr}");
                    }
                }

                foreach (var note in notes)
                {
                    column.Item()
                        .PaddingTop(2)
                        .Text(note)
                        .FontSize(8)
                        .Italic()
                        .FontColor(Colors.Grey.Medium);
                }

                // Critical issue callouts for this switch
                var switchIssues = data.CriticalIssues.Where(i => i.SwitchName == switchDevice.Name).ToList();
                foreach (var issue in switchIssues)
                {
                    var portDisplay = issue.PortIndex.HasValue
                        ? $"Port {issue.PortIndex} ({issue.PortName})"
                        : issue.PortName;

                    column.Item()
                        .PaddingTop(2)
                        .Text($"> {portDisplay}: {issue.RecommendedAction}")
                        .FontSize(8)
                        .Bold()
                        .FontColor(criticalColor);
                }

                column.Item().PaddingBottom(15);
            }
        });
    }

    private void ComposePortTable(IContainer container, SwitchDetail switchDevice)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);
        var lightGray = GetColor(_branding.Colors.LightGray);
        var criticalBg = Color.FromRGB(255, 230, 230);

        var hasIsolation = switchDevice.Ports.Any(p => p.Isolation);

        container.Table(table =>
        {
            if (hasIsolation)
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(35);  // Port
                    columns.RelativeColumn(1.15f);  // Name
                    columns.ConstantColumn(55);  // Link
                    columns.ConstantColumn(50);  // Forward
                    columns.RelativeColumn(1.4f);  // Native VLAN
                    columns.ConstantColumn(45);  // PoE
                    columns.ConstantColumn(55);  // Port Sec
                    columns.ConstantColumn(55);  // Isolation
                    columns.ConstantColumn(70);  // Status
                });
            }
            else
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.ConstantColumn(35);  // Port
                    columns.RelativeColumn(1.3f);  // Name
                    columns.ConstantColumn(60);  // Link
                    columns.ConstantColumn(55);  // Forward
                    columns.RelativeColumn(1.6f);  // Native VLAN
                    columns.ConstantColumn(50);  // PoE
                    columns.ConstantColumn(60);  // Port Sec
                    columns.ConstantColumn(70);  // Status
                });
            }

            // Header
            table.Header(header =>
            {
                void HeaderCell(string text)
                {
                    header.Cell().Background(primaryColor).Padding(4)
                        .Text(text).Bold().FontSize(7).FontColor(Colors.White);
                }

                HeaderCell("Port");
                HeaderCell("Name");
                HeaderCell("Link");
                HeaderCell("Forward");
                HeaderCell("Native VLAN");
                HeaderCell("PoE");
                HeaderCell("Port Sec");
                if (hasIsolation)
                    HeaderCell("Isolation");
                HeaderCell("Status");
            });

            // Rows
            int rowIndex = 0;
            foreach (var port in switchDevice.Ports)
            {
                var (status, statusType) = port.GetStatus(switchDevice.MaxCustomMacAcls > 0);
                var rowBg = statusType == PortStatusType.Critical ? criticalBg
                    : rowIndex % 2 == 0 ? lightGray
                    : Colors.White;

                var nativeVlan = port.NativeVlan.HasValue && !string.IsNullOrEmpty(port.NativeNetwork)
                    ? $"{port.NativeNetwork} ({port.NativeVlan})"
                    : port.Forward == "disabled" ? "—" : "";

                void DataCell(string text)
                {
                    table.Cell().Background(rowBg).Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4)
                        .AlignCenter().Text(text).FontSize(7);
                }

                void DataCellLeft(string text)
                {
                    table.Cell().Background(rowBg).Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(4)
                        .AlignLeft().Text(text.Length > 18 ? text.Substring(0, 16) + ".." : text).FontSize(7);
                }

                DataCell(port.PortIndex.ToString());
                DataCellLeft(port.Name);
                DataCell(port.GetLinkStatus());
                DataCell(port.Forward == "customize" ? "custom" : port.Forward);
                DataCellLeft(nativeVlan);
                DataCell(port.GetPoeStatus());
                DataCell(port.GetPortSecurityStatus());
                if (hasIsolation)
                    DataCell(port.GetIsolationStatus());
                DataCell(status);

                rowIndex++;
            }
        });
    }

    private void ComposePortSecuritySummary(IContainer container, ReportData data)
    {
        var primaryColor = GetColor(_branding.Colors.Primary);

        container.Column(column =>
        {
            column.Item()
                .PaddingBottom(10)
                .Text("Port Security Coverage Summary")
                .FontSize(16)
                .Bold()
                .FontColor(primaryColor);

            column.Item().Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2.2f);
                    columns.ConstantColumn(70);
                    columns.ConstantColumn(80);
                    columns.RelativeColumn(1.3f);
                    columns.RelativeColumn(1.3f);
                });

                // Header
                var headerBg = GetColor(_branding.Colors.Primary);
                table.Header(header =>
                {
                    header.Cell().Background(headerBg).Padding(6)
                        .Text("Switch").Bold().FontSize(9).FontColor(Colors.White);
                    header.Cell().Background(headerBg).Padding(6)
                        .Text("Total").Bold().FontSize(9).FontColor(Colors.White);
                    header.Cell().Background(headerBg).Padding(6)
                        .Text("Disabled").Bold().FontSize(9).FontColor(Colors.White);
                    header.Cell().Background(headerBg).Padding(6)
                        .Text("MAC Restricted").Bold().FontSize(9).FontColor(Colors.White);
                    header.Cell().Background(headerBg).Padding(6)
                        .Text("Unprotected Active").Bold().FontSize(9).FontColor(Colors.White);
                });

                // Rows
                foreach (var switchDevice in data.Switches)
                {
                    var macStr = switchDevice.MaxCustomMacAcls > 0
                        ? switchDevice.MacRestrictedPorts.ToString()
                        : "0 (no ACL support)";

                    table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                        .AlignLeft().Text(switchDevice.Name).FontSize(9);
                    table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                        .AlignCenter().Text(switchDevice.TotalPorts.ToString()).FontSize(9);
                    table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                        .AlignCenter().Text(switchDevice.DisabledPorts.ToString()).FontSize(9);
                    table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                        .AlignCenter().Text(macStr).FontSize(9);
                    table.Cell().Border(0.5f).BorderColor(Colors.Grey.Lighten2).Padding(6)
                        .AlignCenter().Text(switchDevice.UnprotectedActivePorts.ToString()).FontSize(9);
                }
            });
        });
    }

    private string GetColor(string hexColor)
    {
        // QuestPDF uses hex colors directly
        return hexColor;
    }
}
