#!/bin/bash
#
# Network Optimizer Agent - On-boot setup script for UniFi Dream Machine/Cloud Gateway
# Place this file in /data/on_boot.d/ and make it executable
#
# This script is self-contained and idempotent. It will:
# - Install required dependencies
# - Generate all necessary agent scripts if missing
# - Set up cron jobs for scheduled tasks
# - Start background monitoring processes
# - Can be safely run multiple times without side effects
#
# Author: Network Optimizer Agent
# Version: 1.0
# Compatible: UCG/UDM (busybox/ash compatible)
#

set -e

###############################################################################
# CONFIGURATION VARIABLES
###############################################################################

# Base directory for agent scripts
AGENT_BASE_DIR="/data/network-optimizer-agent"

# Script paths
SQM_MANAGER_SCRIPT="${AGENT_BASE_DIR}/sqm-manager.sh"
SQM_PING_MONITOR_SCRIPT="${AGENT_BASE_DIR}/sqm-ping-monitor.sh"
METRICS_COLLECTOR_SCRIPT="${AGENT_BASE_DIR}/metrics-collector.sh"

# Log files
SETUP_LOG="/var/log/network-optimizer-agent-setup.log"
SQM_LOG="/var/log/sqm-manager.log"
PING_LOG="/var/log/sqm-ping-monitor.log"
METRICS_LOG="/var/log/metrics-collector.log"

# Configuration
INFLUXDB_URL="${INFLUXDB_URL:-http://your-influxdb-host:8086}"
INFLUXDB_TOKEN="${INFLUXDB_TOKEN:-your-token-here}"
INFLUXDB_ORG="${INFLUXDB_ORG:-your-org}"
INFLUXDB_BUCKET="${INFLUXDB_BUCKET:-network-metrics}"

###############################################################################
# LOGGING FUNCTION
###############################################################################

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$SETUP_LOG"
}

###############################################################################
# DEPENDENCY INSTALLATION
###############################################################################

install_dependencies() {
    log "Checking and installing dependencies..."

    # Check for required commands
    local deps_needed=0

    if ! which speedtest > /dev/null 2>&1; then
        log "Installing Ookla Speedtest..."
        # Remove UniFi's bundled speedtest if present
        apt-get remove -y speedtest > /dev/null 2>&1 || true

        # Install official Ookla speedtest
        curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | bash
        apt-get install -y speedtest
        deps_needed=1
    fi

    if ! which bc > /dev/null 2>&1; then
        log "Installing bc (calculator)..."
        apt-get install -y bc
        deps_needed=1
    fi

    if ! which jq > /dev/null 2>&1; then
        log "Installing jq (JSON processor)..."
        apt-get install -y jq
        deps_needed=1
    fi

    if [ $deps_needed -eq 0 ]; then
        log "All dependencies already installed."
    else
        log "Dependencies installation complete."
    fi
}

###############################################################################
# SCRIPT GENERATION FUNCTIONS
###############################################################################

generate_sqm_manager() {
    if [ -f "$SQM_MANAGER_SCRIPT" ]; then
        log "SQM Manager script already exists, skipping generation."
        return 0
    fi

    log "Generating SQM Manager script..."

    cat > "$SQM_MANAGER_SCRIPT" << 'SQMMANAGER_EOF'
#!/bin/bash
# This script will be generated by the setup script
# See sqm-manager.sh for full implementation
echo "SQM Manager placeholder - should be replaced during installation"
exit 1
SQMMANAGER_EOF

    chmod +x "$SQM_MANAGER_SCRIPT"
    log "SQM Manager script generated at $SQM_MANAGER_SCRIPT"
}

generate_sqm_ping_monitor() {
    if [ -f "$SQM_PING_MONITOR_SCRIPT" ]; then
        log "SQM Ping Monitor script already exists, skipping generation."
        return 0
    fi

    log "Generating SQM Ping Monitor script..."

    cat > "$SQM_PING_MONITOR_SCRIPT" << 'SQMPING_EOF'
#!/bin/bash
# This script will be generated by the setup script
# See sqm-ping-monitor.sh for full implementation
echo "SQM Ping Monitor placeholder - should be replaced during installation"
exit 1
SQMPING_EOF

    chmod +x "$SQM_PING_MONITOR_SCRIPT"
    log "SQM Ping Monitor script generated at $SQM_PING_MONITOR_SCRIPT"
}

generate_metrics_collector() {
    if [ -f "$METRICS_COLLECTOR_SCRIPT" ]; then
        log "Metrics Collector script already exists, skipping generation."
        return 0
    fi

    log "Generating Metrics Collector script..."

    cat > "$METRICS_COLLECTOR_SCRIPT" << 'METRICS_EOF'
#!/bin/bash
# This script will be generated by the setup script
# See metrics-collector.sh for full implementation
echo "Metrics Collector placeholder - should be replaced during installation"
exit 1
METRICS_EOF

    chmod +x "$METRICS_COLLECTOR_SCRIPT"
    log "Metrics Collector script generated at $METRICS_COLLECTOR_SCRIPT"
}

###############################################################################
# CRON JOB SETUP
###############################################################################

setup_cron_jobs() {
    log "Setting up cron jobs..."

    # Remove existing cron jobs for these scripts (idempotent cleanup)
    (crontab -l 2>/dev/null | grep -v "$SQM_MANAGER_SCRIPT" | grep -v "$SQM_PING_MONITOR_SCRIPT" | grep -v "$METRICS_COLLECTOR_SCRIPT") | crontab - 2>/dev/null || true

    # Add new cron jobs
    (
        crontab -l 2>/dev/null || true
        # SQM Manager: Run speedtest at 6 AM and 6:30 PM
        echo "0 6 * * * export PATH=\"\$PATH\"; export HOME=/root; $SQM_MANAGER_SCRIPT >> $SQM_LOG 2>&1"
        echo "30 18 * * * export PATH=\"\$PATH\"; export HOME=/root; $SQM_MANAGER_SCRIPT >> $SQM_LOG 2>&1"

        # SQM Ping Monitor: Every 5 minutes (skip during speedtest windows)
        echo "*/5 * * * * export PATH=\"\$PATH\"; export HOME=/root; if [ \"\$(date +\\%H:\\%M)\" != \"06:00\" ] && [ \"\$(date +\\%H:\\%M)\" != \"18:30\" ]; then $SQM_PING_MONITOR_SCRIPT >> $PING_LOG 2>&1; fi"

        # Metrics Collector: Every minute
        echo "* * * * * export PATH=\"\$PATH\"; export HOME=/root; $METRICS_COLLECTOR_SCRIPT >> $METRICS_LOG 2>&1"
    ) | crontab -

    log "Cron jobs configured successfully."
}

###############################################################################
# SERVICE STARTUP
###############################################################################

start_services() {
    log "Starting background services..."

    # Run initial speedtest calibration after 30 seconds
    log "Scheduling initial SQM calibration to run in 30 seconds..."
    systemd-run --on-active=30sec --timer-property=AccuracySec=1s \
        --setenv=PATH="$(echo $PATH)" \
        --setenv=HOME=/root \
        "$SQM_MANAGER_SCRIPT" >> "$SQM_LOG" 2>&1 &

    log "Background services started."
}

###############################################################################
# MAIN EXECUTION
###############################################################################

main() {
    log "========================================="
    log "Network Optimizer Agent Setup Starting"
    log "========================================="

    # Create base directory if it doesn't exist
    if [ ! -d "$AGENT_BASE_DIR" ]; then
        log "Creating agent base directory: $AGENT_BASE_DIR"
        mkdir -p "$AGENT_BASE_DIR"
    fi

    # Install dependencies
    install_dependencies

    # Generate scripts if they don't exist
    # Note: In production, these would be copied from install.sh
    # This is a fallback for self-contained deployment
    generate_sqm_manager
    generate_sqm_ping_monitor
    generate_metrics_collector

    # Setup cron jobs
    setup_cron_jobs

    # Start services
    start_services

    log "========================================="
    log "Network Optimizer Agent Setup Complete"
    log "========================================="
    log "Logs:"
    log "  Setup: $SETUP_LOG"
    log "  SQM Manager: $SQM_LOG"
    log "  Ping Monitor: $PING_LOG"
    log "  Metrics Collector: $METRICS_LOG"
    log ""
    log "Scripts installed to: $AGENT_BASE_DIR"
    log "========================================="
}

# Run main function
main
